# Generated by Django 3.0.4 on 2020-08-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200723_1544'),
        ('payments', '0002_auto_20200531_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.Order'),
        ),
    ]
