# Generated by Django 3.0.4 on 2020-04-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200409_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistprofile',
            old_name='date_joined',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='collectorprofile',
            old_name='date_joined',
            new_name='created_joined',
        ),
    ]
