# Generated by Django 3.0.4 on 2020-04-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200409_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectorprofile',
            old_name='created_joined',
            new_name='created_on',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
