# Generated by Django 3.0.4 on 2020-06-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200415_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='birth_place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='photo',
            field=models.ImageField(null=True, upload_to='users/profile_photos'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='birth_place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='county',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='photo',
            field=models.ImageField(null=True, upload_to='users/profile_photos'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='county',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
