# Generated by Django 3.0.4 on 2020-08-22 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
