# Generated by Django 3.0.4 on 2020-11-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10),
        ),
    ]
