# Generated by Django 3.0.4 on 2020-08-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rating_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='artist_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.ArtistProfile'),
        ),
    ]
