# Generated by Django 3.0.4 on 2020-08-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200822_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-id']},
        ),
    ]
