# Generated by Django 3.0.4 on 2020-08-23 17:59

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200823_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=1.0, validators=[users.validators.validate_rating]),
        ),
    ]
