# Generated by Django 3.0.4 on 2020-05-03 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20200503_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
