# Generated by Django 3.0.4 on 2020-08-23 18:26

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200823_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, validators=[core.validators.validate_date]),
        ),
    ]
