# Generated by Django 3.0.4 on 2020-03-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
    ]
