# Generated by Django 3.0.4 on 2020-03-29 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_order_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='custom_orders/images')),
                ('description', models.TextField()),
                ('size', models.TextField()),
                ('medium', models.CharField(choices=[('Canvas', 'Canvas'), ('Wood', 'Wood'), ('Soapstone', 'Soap Stone')], max_length=50)),
                ('due_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(limit_choices_to='Artist', on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_artist', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
