# Generated by Django 3.0.4 on 2020-03-29 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_customorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_artist', to=settings.AUTH_USER_MODEL),
        ),
    ]
