# Generated by Django 3.0.4 on 2020-05-14 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_category_cover_photo'),
        ('orders', '0012_auto_20200512_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='CartItem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='CartItem',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_products', to='products.Product'),
        ),
    ]
