# Generated by Django 3.0.4 on 2020-05-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200514_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='CartItem',
            name='quantities',
            field=models.IntegerField(default=1),
        ),
    ]
