# Generated by Django 3.0.4 on 2020-07-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200721_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customorder',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
    ]
