# Generated by Django 3.0.4 on 2020-07-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200721_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customorder',
            old_name='image',
            new_name='picture',
        ),
    ]
