# Generated by Django 3.0.4 on 2020-10-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200723_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'placed'), ('paid', 'paid')], default='placed', max_length=15),
        ),
    ]
