# Generated by Django 3.0.4 on 2020-11-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20201031_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='first_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='last_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
