# Generated by Django 3.0.4 on 2020-11-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20201112_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='orders', to='orders.CartItem'),
        ),
    ]
