# Generated by Django 3.0.4 on 2020-04-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200315_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
