# Generated by Django 3.0.4 on 2020-07-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
