# Generated by Django 3.0.4 on 2020-07-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200721_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='medium',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
