# Generated by Django 3.0.4 on 2020-07-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200721_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medium',
            options={'ordering': ['name']},
        ),
    ]
