# Generated by Django 3.0.4 on 2020-08-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200721_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
