# Generated by Django 3.0.4 on 2020-10-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200823_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='spin_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
