# Generated by Django 3.0.4 on 2020-10-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20201006_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='spin_image',
            field=models.FileField(blank=True, null=True, upload_to='art/3d-images'),
        ),
    ]
